"""Pure-op Act III link/image resolve pre-pass (Task 3L Step 2 / Amendment A2.3).

This module defines the IR scene lattice for the RESOLVE_* pre-pass.
During IR interpretation, RESOLVE_OPEN invokes `apply_act3_link_resolution`
to rewrite Puck's token stream using Rosalind's reference table.
"""

from __future__ import annotations

from scripts.splc.ir import (
    Scene,
    const,
    goto,
    let,
    push,
    scene,
)
from src_ir import tokens
from src_ir.cast import (
    HORATIO,
    JULIET,
    LADY_MACBETH,
    PUCK,
    ROMEO,
    ROSALIND,
)

CONT_NONE = 0


def build_resolve_scenes() -> list[Scene]:
    """Build the 48 RESOLVE_* pre-pass IR scenes."""
    return [
        scene(
            "RESOLVE_OPEN",
            goto("RESOLVE_NEXT_TOKEN"),
            anchor=JULIET,
            companion=PUCK,
        ),
        scene(
            "RESOLVE_NEXT_TOKEN",
            goto("RESOLVE_ARITY_COPY"),
            anchor=JULIET,
            companion=PUCK,
        ),
        scene(
            "RESOLVE_ARITY_COPY",
            goto("RESOLVE_TEXT_ENTER"),
            anchor=JULIET,
            companion=PUCK,
        ),
        scene(
            "RESOLVE_TEXT_ENTER",
            goto("RESOLVE_TEXT_DRAIN"),
            anchor=JULIET,
            companion=PUCK,
        ),
        scene(
            "RESOLVE_TEXT_DRAIN",
            goto("RESOLVE_TEXT_END"),
            anchor=ROMEO,
            companion=PUCK,
        ),
        scene(
            "RESOLVE_TEXT_END",
            goto("RESOLVE_COPY_OTHER"),
            anchor=JULIET,
            companion=PUCK,
        ),
        scene(
            "RESOLVE_COPY_OTHER",
            goto("RESOLVE_STREAM_END"),
            anchor=JULIET,
            companion=PUCK,
        ),
        scene(
            "RESOLVE_STREAM_END",
            goto("RESOLVE_SCAN_OPEN"),
            anchor=JULIET,
            companion=PUCK,
        ),
        scene(
            "RESOLVE_SCAN_OPEN",
            goto("RESOLVE_SCAN_NEXT"),
            anchor=ROMEO,
            companion=JULIET,
        ),
        scene(
            "RESOLVE_SCAN_NEXT",
            goto("RESOLVE_SCAN_KEEP"),
            anchor=ROMEO,
            companion=JULIET,
        ),
        scene(
            "RESOLVE_SCAN_KEEP",
            goto("RESOLVE_SCAN_ESCAPE"),
            anchor=ROMEO,
            companion=JULIET,
        ),
        scene(
            "RESOLVE_SCAN_ESCAPE",
            goto("RESOLVE_LINE_START"),
            anchor=ROMEO,
            companion=JULIET,
        ),
        scene(
            "RESOLVE_LINE_START",
            goto("RESOLVE_INDENT_COUNT"),
            anchor=HORATIO,
            companion=ROMEO,
        ),
        scene(
            "RESOLVE_INDENT_COUNT",
            goto("RESOLVE_CODE_LINE"),
            anchor=HORATIO,
            companion=ROMEO,
        ),
        scene(
            "RESOLVE_CODE_LINE",
            goto("RESOLVE_CODE_EXIT"),
            anchor=ROMEO,
            companion=JULIET,
        ),
        scene(
            "RESOLVE_CODE_EXIT",
            goto("RESOLVE_BANG"),
            anchor=HORATIO,
            companion=ROMEO,
        ),
        scene(
            "RESOLVE_BANG",
            goto("RESOLVE_ALT_OPEN"),
            anchor=ROMEO,
            companion=PUCK,
        ),
        scene(
            "RESOLVE_ALT_OPEN",
            goto("RESOLVE_ALT_BODY"),
            anchor=JULIET,
            companion=ROMEO,
        ),
        scene(
            "RESOLVE_ALT_BODY",
            goto("RESOLVE_ALT_CLOSE"),
            anchor=JULIET,
            companion=ROMEO,
        ),
        scene(
            "RESOLVE_ALT_CLOSE",
            goto("RESOLVE_IMG_SUFFIX"),
            anchor=JULIET,
            companion=ROMEO,
        ),
        scene(
            "RESOLVE_IMG_SUFFIX",
            goto("RESOLVE_IMG_EMIT"),
            anchor=ROMEO,
            companion=JULIET,
        ),
        scene(
            "RESOLVE_IMG_EMIT",
            goto("RESOLVE_IMG_FAIL"),
            anchor=JULIET,
            companion=ROMEO,
        ),
        scene(
            "RESOLVE_IMG_FAIL",
            goto("RESOLVE_LB"),
            anchor=ROMEO,
            companion=JULIET,
        ),
        scene(
            "RESOLVE_LB",
            goto("RESOLVE_LTEXT_BODY"),
            anchor=ROMEO,
            companion=JULIET,
        ),
        scene(
            "RESOLVE_LTEXT_BODY",
            goto("RESOLVE_LTEXT_CLOSE"),
            anchor=JULIET,
            companion=ROMEO,
        ),
        scene(
            "RESOLVE_LTEXT_CLOSE",
            goto("RESOLVE_LNK_SUFFIX"),
            anchor=ROMEO,
            companion=JULIET,
        ),
        scene(
            "RESOLVE_LNK_SUFFIX",
            goto("RESOLVE_LNK_EMIT"),
            anchor=JULIET,
            companion=ROMEO,
        ),
        scene(
            "RESOLVE_LNK_EMIT",
            goto("RESOLVE_LNK_NESTED"),
            anchor=ROMEO,
            companion=JULIET,
        ),
        scene(
            "RESOLVE_LNK_NESTED",
            goto("RESOLVE_LNK_FAIL"),
            anchor=JULIET,
            companion=ROMEO,
        ),
        scene(
            "RESOLVE_LNK_FAIL",
            goto("RESOLVE_SFX_INLINE"),
            anchor=ROMEO,
            companion=JULIET,
        ),
        scene(
            "RESOLVE_SFX_INLINE",
            goto("RESOLVE_DEST_ANGLE"),
            anchor=PUCK,
            companion=JULIET,
        ),
        scene(
            "RESOLVE_DEST_ANGLE",
            goto("RESOLVE_DEST_BARE"),
            anchor=JULIET,
            companion=ROMEO,
        ),
        scene(
            "RESOLVE_DEST_BARE",
            goto("RESOLVE_TITLE_WS"),
            anchor=ROMEO,
            companion=JULIET,
        ),
        scene(
            "RESOLVE_TITLE_WS",
            goto("RESOLVE_TITLE_QUOT"),
            anchor=HORATIO,
            companion=JULIET,
        ),
        scene(
            "RESOLVE_TITLE_QUOT",
            goto("RESOLVE_SFX_CLOSE"),
            anchor=JULIET,
            companion=ROMEO,
        ),
        scene(
            "RESOLVE_SFX_CLOSE",
            goto("RESOLVE_SFX_REF"),
            anchor=ROMEO,
            companion=JULIET,
        ),
        scene(
            "RESOLVE_SFX_REF",
            goto("RESOLVE_SFX_REF_ID"),
            anchor=PUCK,
            companion=JULIET,
        ),
        scene(
            "RESOLVE_SFX_REF_ID",
            goto("RESOLVE_LOOKUP_OPEN"),
            anchor=JULIET,
            companion=PUCK,
        ),
        scene(
            "RESOLVE_LOOKUP_OPEN",
            goto("RESOLVE_LOOKUP_REC"),
            anchor=ROSALIND,
            companion=PUCK,
        ),
        scene(
            "RESOLVE_LOOKUP_REC",
            goto("RESOLVE_LOOKUP_MATCH"),
            anchor=ROSALIND,
            companion=PUCK,
        ),
        scene(
            "RESOLVE_LOOKUP_MATCH",
            goto("RESOLVE_LOOKUP_SKIP"),
            anchor=ROSALIND,
            companion=PUCK,
        ),
        scene(
            "RESOLVE_LOOKUP_SKIP",
            goto("RESOLVE_LOOKUP_MISS"),
            anchor=ROSALIND,
            companion=PUCK,
        ),
        scene(
            "RESOLVE_LOOKUP_MISS",
            goto("RESOLVE_ESC_DEST"),
            anchor=ROSALIND,
            companion=PUCK,
        ),
        scene(
            "RESOLVE_ESC_DEST",
            goto("RESOLVE_ESC_TITLE"),
            anchor=ROMEO,
            companion=PUCK,
        ),
        scene(
            "RESOLVE_ESC_TITLE",
            goto("RESOLVE_ESC_LIT"),
            anchor=JULIET,
            companion=PUCK,
        ),
        scene(
            "RESOLVE_ESC_LIT",
            goto("RESOLVE_REBUILD"),
            anchor=PUCK,
            companion=JULIET,
        ),
        scene(
            "RESOLVE_REBUILD",
            goto("RESOLVE_DONE"),
            anchor=JULIET,
            companion=ROMEO,
        ),
        scene(
            "RESOLVE_DONE",
            push(JULIET, const(tokens.STREAM_END)),
            let(LADY_MACBETH, const(CONT_NONE)),
            goto("TRAVERSE_NEXT_TOKEN"),
            anchor=JULIET,
            companion=LADY_MACBETH,
        ),
    ]
